AWSTemplateFormatVersion: 2010-09-09
Description: Scratch template for enabling security hub

Parameters:
  ServiceCode:
    Description: The code attached to the service which costs are attributed to
    Type: String

  ServiceName:
    Description: The name of the service which costs are attributed to
    Type: String

  ServiceOwner:
    Description: The owners of the service which costs are attributed to
    Type: String
  
Resources:
  CloudTeamHub:
    Type: "AWS::SecurityHub::Hub"
    Properties:
      Tags:
        ServiceCode: !Ref ServiceCode
        ServiceName: !Ref ServiceName
        ServiceOwner: !Ref ServiceOwner
  
  InviteNewMemberRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
      Description: String
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyDocument:
            Statement:
            - Action:
              - securityhub:BatchEnableStandards
              - securityhub:CreateMembers
              - securityhub:DeleteMembers
              - securityhub:Describe*
              - securityhub:Get*
              - securityhub:InviteMembers
              - securityhub:List*
              Effect: Allow
              Resource: !Sub "arn:aws:securityhub:${AWS::Region}:${AWS::AccountId}:hub/default"
          PolicyName: InviteNewMembersLambdaPolicy
      RoleName: InviteNewMembersLambdaRole
      Tags:
        - Key: ServiceCode
          Value: !Ref ServiceCode
        - Key: ServiceName
          Value: !Ref ServiceName
        - Key: ServiceOwner
          Value: !Ref ServiceOwner
  
  InviteNewMemberAccount:
    Type: "AWS::Lambda::Function"
    Properties:
      Code: packages/deploy-function
      Description: Invites Member Account to Security Hub
      Handler: index.lambda_handler
      MemorySize: 1024
      Role: !GetAtt InviteNewMemberRole.Arn
      Runtime: python3.8
      Tags:
        - Key: ServiceCode
          Value: !Ref ServiceCode
        - Key: ServiceName
          Value: !Ref ServiceName
        - Key: ServiceOwner
          Value: !Ref ServiceOwner
      Timeout: 300

Outputs:
  SecurityHubArn:
    Value: !Ref CloudTeamHub
